



DROP DATABASE IF EXISTS EVENEMENTS;
CREATE DATABASE IF NOT EXISTS EVENEMENTS;
USE EVENEMENTS;

DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS A_LIEU;
DROP TABLE IF EXISTS EVENEMENT;
DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS THEME;
DROP TABLE IF EXISTS CONCERNE;
DROP TABLE IF EXISTS INSCRIT;
DROP TABLE IF EXISTS VISITEUR;
DROP TABLE IF EXISTS ADMINISTRATEUR;
DROP TABLE IF EXISTS CREERSUPPRIMER;
DROP TABLE IF EXISTS CONTRIBUTEUR;



CREATE TABLE LIEU (
  idlieu INTEGER NOT NULL AUTO_INCREMENT,
  ville VARCHAR(42),
  rue VARCHAR(42),
  numero_rue NUMERIC(5),
  code_postal VARCHAR(42),
  position_long DECIMAL(14,11),
  position_lat DECIMAL(14,11),
  CONSTRAINT PK_LIEU PRIMARY KEY (idlieu)
) ENGINE=InnoDB ;

CREATE TABLE A_LIEU (
  idlieu INTEGER NOT NULL,
  idevent INTEGER NOT NULL,
  CONSTRAINT PK_A_LIEU PRIMARY KEY (idlieu, idevent)
) ENGINE=InnoDB ;

CREATE TABLE EVENEMENT (
  idevent INTEGER NOT NULL AUTO_INCREMENT,
  nomEvent VARCHAR(42),
  dateEvent DATE,
  effectif_min NUMERIC(10),
  effectif_max NUMERIC(10),
  idcontrib INTEGER NOT NULL,
  idtheme INTEGER NOT NULL,
  idlieu INTEGER NOT NULL,
  description TEXT,
  dateCRE_E_SUP_E DATE,
  CONSTRAINT PK_EVENEMENT PRIMARY KEY (idevent)
) ENGINE=InnoDB;

CREATE TABLE NOTE (
  idevent INTEGER NOT NULL,
  idvisit  INTEGER NOT NULL,
  note NUMERIC(2),
  commentaire VARCHAR(42),
  CONSTRAINT NOTE_PK PRIMARY KEY (idevent,idvisit)
) ENGINE=InnoDB ;

CREATE TABLE THEME (
  idtheme INTEGER NOT NULL AUTO_INCREMENT,
  nom VARCHAR(42),
  categorie VARCHAR(42),
  idadmin INTEGER,
  dateCRE_T_SUP_T DATE,
  CONSTRAINT PK_THEME PRIMARY KEY (idtheme)
) ENGINE=InnoDB ;

CREATE TABLE CONCERNE (
  idevent INTEGER NOT NULL,
  idtheme INTEGER NOT NULL,
  CONSTRAINT PK_CONCERNE PRIMARY KEY (idevent, idtheme)
) ENGINE=InnoDB ;

CREATE TABLE INSCRIT (
  idevent INTEGER NOT NULL,
  idvisit INTEGER NOT NULL,
  dateINS DATE,
  CONSTRAINT PK_INSCRIT PRIMARY KEY (idevent, idvisit)
) ENGINE=InnoDB ;

CREATE TABLE VISITEUR (
  idvisit INTEGER NOT NULL AUTO_INCREMENT,
  email VARCHAR(42),
  nom VARCHAR(42),
  prenom VARCHAR(42),
  age NUMERIC(3,0),
  pseudo VARCHAR(42),
password VARCHAR(70),
  CONSTRAINT PK_VISITEUR PRIMARY KEY (idvisit)
) ENGINE=InnoDB ;

CREATE TABLE ADMINISTRATEUR (
  idadmin INTEGER NOT NULL AUTO_INCREMENT,
  nom VARCHAR(42),
  prenom VARCHAR(42),
  email VARCHAR(42),
  password VARCHAR(70),
  CONSTRAINT PK_ADMINISTRATEUR PRIMARY KEY (idadmin)
) ENGINE=InnoDB ;

CREATE TABLE CREER_SUPPRIMER_CONTRIB (
  idcontrib INTEGER NOT NULL,
  idadmin INTEGER NOT NULL,
  dateCRE_C_SUP_C DATE,
  CONSTRAINT PK_CREERSUPPRIMER_CONTRIB PRIMARY KEY (idcontrib, idadmin)
) ENGINE=InnoDB ;

CREATE TABLE CONTRIBUTEUR (
  idcontrib INTEGER NOT NULL AUTO_INCREMENT,
  idadmin INTEGER NOT NULL,
  email VARCHAR(42),
  nom VARCHAR(42),
  prenom VARCHAR(42),
  age VARCHAR(42),
  pseudo VARCHAR(42),
  password VARCHAR(70),
  CONSTRAINT PK_CONTRIBUTEUR PRIMARY KEY (idcontrib)
) ENGINE=InnoDB;

